// Real Delhi NCR colleges/universities. Curated list of major institutions.
// IMPORTANT: SDGI Global University comes FIRST in Ghaziabad — that is where the app is launching.

import { City } from "./data";

export const COLLEGES: Record<City, string[]> = {
  Ghaziabad: [
    "SDGI Global University",                       // Launch partner — keep first
    "ABES Engineering College",
    "KIET Group of Institutions",
    "Ajay Kumar Garg Engineering College (AKGEC)",
    "Inderprastha Engineering College (IPEC)",
    "IMS Ghaziabad",
    "Raj Kumar Goel Institute of Technology (RKGIT)",
    "ITS Engineering College",
    "HRIT (Hindustan Institute of Technology)",
    "Dr. KN Modi Foundation",
    "ICRI Ghaziabad",
    "IIMT University",
    "Ginni Devi Modi Institute of Technology",
  ],
  Delhi: [
    "IIT Delhi",
    "AIIMS Delhi",
    "Delhi University — North Campus",
    "Delhi University — South Campus",
    "Hindu College",
    "Hansraj College",
    "St. Stephen's College",
    "Miranda House",
    "Lady Shri Ram College (LSR)",
    "Shri Ram College of Commerce (SRCC)",
    "Kirori Mal College",
    "Ramjas College",
    "Sri Venkateswara College",
    "Gargi College",
    "Jawaharlal Nehru University (JNU)",
    "Jamia Millia Islamia",
    "IIIT Delhi",
    "Delhi Technological University (DTU)",
    "Netaji Subhas University of Technology (NSUT)",
    "GGSIPU (IP University)",
    "IGNOU",
    "National Law University, Delhi",
  ],
  Gurugram: [
    "Amity University Gurugram",
    "Ansal University",
    "K.R. Mangalam University",
    "ITM University",
    "SGT University",
    "Manav Rachna University, Gurugram",
    "The NorthCap University",
    "GD Goenka University",
    "World University of Design",
    "Pearl Academy Gurugram",
  ],
  Noida: [
    "Amity University Noida",
    "Jaypee Institute of Information Technology (JIIT)",
    "Bennett University",
    "Galgotias University",
    "Shiv Nadar University (Greater Noida)",
    "Sharda University",
    "IILM University Greater Noida",
    "Noida International University",
    "GL Bajaj Institute of Technology",
    "ABES Engineering College, Noida",
    "Asian Business School",
    "IMS Noida",
    "JSS Academy of Technical Education",
  ],
  Faridabad: [
    "Manav Rachna University",
    "YMCA University of Science and Technology",
    "Lingaya's Vidyapeeth",
    "Apeejay Stya University",
    "Aravali College of Engineering",
    "JC Bose University of Science and Technology",
    "DAV Centenary College",
    "Faridabad Institute of Technology",
  ],
};
